### ISSUE TITLE
Call to a member function alias() on a non-object

### ISSUE THREAD

**Issue by myconcretelab** [concrete5/addon_sample_content_generator#3]
Yesterday, during all the day i has try to get this working but in vain.
In different instalation, different configuration, different starting point i have always the same error that stop importing : Call to a member function alias() on a non-object from ContentImporter.php

```
                                $mc = Page::getByID($page->getMasterCollectionID(), 'RECENT');
                                $block = Block::getByID($bID, $mc, (string)$ax['name']);
                                $block->alias($page);
```

The site source is clean, installed from blank starti,ng point and build for demo : http://vedana.myconcretelab.com/

I can't work with this for simplesite.

**Comment by aembler** [comment]
I'm not sure, but I have a thought. If you look through your xml, can you find all instances of a block with the attribute mc-block-id? Everywhere that block is used, it should map to another instance of a block actually being output in a defaults. For example, if you ever see a <block> node with mc-block-id and no other content, there HAS to be a block in a defaults page for that page type/template that has the exact same mc-block-id. That's how we handle aliasing in the content exporter.

Here's what I bet happened. You exported content, pasted it in, etc... Tried to import content, something failed (as often happens.) Then you export content again, and try and make fixes. Unfortunately, mc-block-id is regenerated every time you run the exporter. So now you might have some blocks that are out of sync.

You don't have to worry about WHAT the mc-block-id is. It could be "andrewe" or "myconcretelabblock123" all that matters is that wherever it appears, there's a corresponding block in the page type defaults that has the same identifier. 

Does this help? You

**Comment by myconcretelab** [comment]
Actually, I already understood and tried this but I have more than 140 occurrences to check and I lost courage.
I tried with another site, most imple, I checked that no block was from the clipboard (which I suspected to be responsible for errors) and I met other block duplication errors -type, and finally a mistake I not understand and that discouraged me.
In fact the debate is broader. I do not understand why this process is bugged for years.
I received an email from Franz, asking me to participate in SimpleSite project, I guess I'm not the only one and I find myself bewildered by the care given to the poverty method for providing a sample content. Why not bring the care to the script, take potential errors expenses (not to install a block if it is not properly referenced, check duplicates, ...) and enable in the theme of developers to raise raising the niveu C5 quality service?
Perhaps my point is moved or rude, in this case I apologize, but I spent three days in frustration as I really wanted to produce professional content for Concrete5.

Maybe imagine develop the script for the instalation of a sample contents either insatlation of Concrete5 with a loading bar, a little ajax and information about the current steps. I think if the sample content becomes important to the program SimpleSite, it is important not to let the user wait 15 minutes without information during the instalation. 
I would like to help develop this part of Concrete5.

**Comment by aembler** [comment]
Sorry to hear you're having trouble.

Yes, we definitely should give better feedback during the content importing period. That would go a long way toward making it easier to figure out what's going on when something goes wrong.

I don't think the format is inherently flawed, as we have used the format for years to specify our sample content, and other theme developers have been able to get their sample content going. But it is not easy and it can be a painful process, which we would like to make easier. We would be happy to except pull requests and improvements to the format itself that would make it easier to debug problems.

Going forward, we would like to make this format the basis for a 5.6 -> 5.7 migration utility, so improvements made to import would likely improve that process as well.

**Comment by myconcretelab** [comment]
Thanks Andrew. I would help to improve import process. I will check this

**Comment by katalysis** [comment]
I'm seeing this issue too.  Content import works without blocks if all mc-block-id entries are commented out. I've tested this several times and the import still fails if blocks are included despite them being referenced in the default page types.
