### ISSUE TITLE
Fatal error: Call to a member function canRead() on a non-object in ..concrete5.6.3.3/concrete/single_pages/dashboard/sitemap/explore.php on line 19

### ISSUE THREAD

**Issue by sureshamk** [concrete5/addon_sample_content_generator#5]
Hii , 

i Used the Market places , package , with version 5.6.3.3 , files generated fine but with generate content i'm getting following issue 

Fatal error: Call to a member function canRead() on a non-object in ..concrete5.6.3.3/concrete/single_pages/dashboard/sitemap/explore.php on line 19

**Comment by 2keepConcrete5** [comment]
Just FYI as an update, I ran this utility on my bluehost account and I did not encounter this error. I did however have to manually copy and paste the file into a textedit file and am now trying to figure out how to map this to 5.7.3.

Have you tried to backup your database and website files and then reinstall 5.6.3.3 and this add_on to correct that issue?  Best wishes,

Rob Smith
TeachingSupportDesk.com

**Comment by 2keepConcrete5** [comment]
FYI, you might even just try to reinstall the add_on first and see if that fixes the problem... - R

**Comment by VincentMolinie** [comment]
Hi,
Did you found a solution to your problem ? I  have the same issue.
I tried to reinstall concrete but it didn't worked and same for the add-on.

**Comment by aembler** [comment]
It's highly recommended that you use the absolute latest version of concrete5 5.6 when you're using this add-on.

**Comment by VincentMolinie** [comment]
I've tried to downgrade to 5.6.0 but now I have like 200 errors printed. I have a lot of "should not be called statically" or "undefined property".

**Comment by KorvinSzanto** [comment]
@VincentMolinie From what I see E_STRICT should be disabled: https://github.com/concrete5/concrete5-legacy/blob/131aa463ab6d25a6cdd6c75027491bbd9b0c3df9/web/concrete/dispatcher.php

**Comment by VincentMolinie** [comment]
@KorvinSzanto Oups sorry, my bad I put an E_ALL.
I had then to rename QueueableJob to Concrete5_Model_QueueableJob in search_index_all.php and that was working.
Thanks for your help !

**Comment by aberbenni** [comment]
Any solution yet?

I'm having same Fatal error: Call to a member function canRead() on a non-object in .../concrete/single_pages/dashboard/sitemap/explore.php on line 19

On concrete5.6.3.3.

**Comment by aberbenni** [comment]
Same error on a freshly installed, empty, Concrete5.6.3.4.

**Comment by VincentMolinie** [comment]
> Oups sorry, my bad I put an E_ALL.
> I had then to rename QueueableJob to Concrete5_Model_QueueableJob in
> search_index_all.php and that was working.
> Thanks for your help !

That was the solution

2016-03-01 10:20 GMT-05:00 Alessandro Berbenni notifications@github.com:

> Any solution yet?
> 
> I'm having same Fatal error: Call to a member function canRead() on a
> non-object in .../concrete/single_pages/dashboard/sitemap/explore.php on
> line 19
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/concrete5/addon_sample_content_generator/issues/5#issuecomment-190768003
> .

## 

Molinié Vincent
ING3 - Professeur BioInformatique 2015 - EPITA

**Comment by aberbenni** [comment]
I have changed line 9 of /concrete/core/jobs/index_search_all.php

`class Concrete5_Job_IndexSearchAll extends Concrete5_Model_QueueableJob { //QueueableJob {`

But nothing changed.

**Comment by VincentMolinie** [comment]
Sorry but I only remember that

2016-03-01 10:40 GMT-05:00 Alessandro Berbenni notifications@github.com:

> I have changed line 9 of /concrete/core/jobs/index_search_all.php
> 
> class Concrete5_Job_IndexSearchAll extends Concrete5_Model_QueueableJob {
> //QueueableJob {
> 
> But nothing changed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/concrete5/addon_sample_content_generator/issues/5#issuecomment-190776042
> .

## 

Molinié Vincent
ING3 - Professeur BioInformatique 2015 - EPITA

**Comment by aberbenni** [comment]
I think this change is useless because /concrete/models/queueable_job.php already extend Concrete5_Model_QueueableJob

`abstract class QueueableJob extends Concrete5_Model_QueueableJob {}`

and /concrete/core/jobs/index_search_all.php extends QueueableJob ...

**Comment by VincentMolinie** [comment]
It fix everything for me because He couldn't find QueuableJob

2016-03-01 10:43 GMT-05:00 Alessandro Berbenni notifications@github.com:

> I think this change is useless because /concrete/models/queueable_job.php
> already extend Concrete5_Model_QueueableJob
> 
> abstract class QueueableJob extends Concrete5_Model_QueueableJob {}
> 
> and /concrete/core/jobs/index_search_all.php extends QueueableJob ...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/concrete5/addon_sample_content_generator/issues/5#issuecomment-190777037
> .

## 

Molinié Vincent
ING3 - Professeur BioInformatique 2015 - EPITA

**Comment by aberbenni** [comment]
Which version of Concrete5?
