### ISSUE TITLE
Got issue when installing add-on

### ISSUE THREAD

**Issue by Jonathanh99** [concrete5/addon_sample_content_generator#7]
When I installed Sample Content generator addon, the addon page got issue like attached file show
![My issue](https://cloud.githubusercontent.com/assets/29224353/26819487/460fbff2-4ac9-11e7-9f57-75c82d48a803.png)
The code is fine through PHP validator. I don't know why. Can you tell me how to fix it?

**Comment by KorvinSzanto** [comment]
Looks like this package requires short tags be enabled.
